version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: "direct"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
      react:
        patterns:
          - "react"
          - "react-dom"
    commit-message:
      prefix: "npm"
      include: "scope"