// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a custom sidebar
  apiSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'introduction',
          label: 'Introduction',
        },
        {
          type: 'doc',
          id: 'quickstart',
          label: 'Quickstart',
        },
        {
          type: 'doc',
          id: 'authentication',
          label: 'Authentication',
        },
      ],
    },
    {
      type: 'doc',
      id: 'api-reference',
      label: 'API Reference',
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        {
          type: 'doc',
          id: 'cors',
          label: 'CORS',
        },
        {
          type: 'doc',
          id: 'rate-limits',
          label: 'Rate Limits',
        },
        {
          type: 'doc',
          id: 'pagination',
          label: 'Pagination',
        },
        {
          type: 'doc',
          id: 'errors',
          label: 'Error Codes',
        },
        {
          type: 'doc',
          id: 'webhooks',
          label: 'Webhooks',
          className: 'sidebar-item-beta',
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        { type: 'doc', id: 'attributes', label: 'Attributes' },
        { type: 'doc', id: 'actor-profiles', label: 'Actor Profiles' },
        { type: 'doc', id: 'crew-profiles', label: 'Crew Profiles' },
        { type: 'doc', id: 'talent-agencies', label: 'Talent Agencies' },
        { type: 'doc', id: 'blog-posts', label: 'Blog Posts' },
        { type: 'doc', id: 'showreels', label: 'Showreels' },
        { type: 'doc', id: 'showreel-media', label: 'Showreel Media' },
        { type: 'doc', id: 'messages', label: 'Messages', className: 'sidebar-item-beta' },
        { type: 'doc', id: 'casting-calls', label: 'Casting Calls', className: 'sidebar-item-beta' },
      ],
    },
    {
      type: 'doc',
      id: 'changelog',
      label: 'Changelog',
    },
  ],
};

export default sidebars;
